Add missing class
godotengine/godot-website pull request #104
Opened 2019-11-29 13:48 UTC by AinaSG

Those 2 sponsors had the logo partially hidden and the wrong hover over animation.

2019-12-02 10:15 UTC, Calinou requested changes

2019-12-02 10:15 UTC, Calinou commented on themes/godotengine/layouts/home.htm
> +      <a class="sponsor card  base-padding" href="https://www.moonwards.com/" target="_blank">
Nitpick, but there should only be one space to separate each CSS class :slightly_smiling_face:

2019-12-02 10:15 UTC, Calinou commented on themes/godotengine/layouts/home.htm
> +      <a class="sponsor card  base-padding" href="https://www.imagecampus.edu.ar/" target="_blank">
Same as above.

2019-12-02 11:17 UTC, AinaSG commented on themes/godotengine/layouts/home.htm
> +      <a class="sponsor card  base-padding" href="https://www.imagecampus.edu.ar/" target="_blank">
Upsies

2019-12-26 15:00 UTC, Calinou commented
It seems the current [Moonwards logo](https://godotengine.org/themes/godotengine/assets/home/sponsors/moonwards.png) is cropped by design (to make its height more reasonable), so I'll close this.

Also, Image Campus is no longer sponsoring Godot.

2019-12-26 15:00 UTC, closed without merging

2020-01-07 13:46 UTC, AinaSG commented
Then maybe it would be better crop the image? because the class with the animation and the margins is in all the other sponsors, right now it's not visible but if we add another sponsor without this one having the class, the animations break bad time.