Chore - Create next and previous buttons below the articles
godotengine/godot-website pull request #629
Opened 2023-04-21 17:53 UTC by a2937

I created a very simple div in the article layout right below the article. If there is previous url, it adds a hyperlink to the previous article. And if there is another article after that one, it adds a link to it. 

Closes #419

2024-08-24 22:03 UTC, Calinou requested changes
Tested locally (rebased on top of `master` https://github.com/godotengine/godot-website/commit/f19d8fd197a939e40208a600a3cc53cb0e81bb22), it works as expected. Sorry for the delay in reviewing.

The navigation is functional, but there's not really much design going around the previous/next links, so they look out of place:

![image](https://github.com/user-attachments/assets/b1f0fad7-3104-4c01-bbc1-6ba6abdb4eec)

___

![image](https://github.com/user-attachments/assets/32f288ce-8540-4704-b5dd-4daf6b400963)

I suggest adding padding around the `previous-next` class, and perhaps give it a background color similar to the article as well.

Also, it might be a good idea to repeat this previous-next block at the top of the article for easier navigation (i.e. the controls should be both at the top and bottom of the article).

2024-08-24 22:04 UTC, Calinou commented on _layouts/article.html
> +  }
Use tab indentation only:

```suggestion
	.next {
		float: right;
	}
```

2024-08-24 22:04 UTC, Calinou commented on _layouts/article.html
> +
Use a single blank line only:

```suggestion

```

2024-08-24 22:04 UTC, Calinou commented on _layouts/article.html
> +		<div class="Previous-next">
Use lowercase class name:

```suggestion
		<div class="previous-next">
```

2024-08-26 10:26 UTC, coppolaemilio commented
I've made some design changes, but I'm not a fan of the feature. It seems useful when you first hear about it, but when do you want to navigate this way?

I doubt anyone would actually use it to browse articles, and it might be much much better to just have a link back to the full blog, where you have the search bar, the categories, etc...

So, if no one is super crazy about this feature I would advice against it, but if you all think it should be added here are the changes I made. I can push to this PR if you like them:

## Desktop
![image](https://github.com/user-attachments/assets/e5decf44-dcda-450a-b255-516205f32798)
![image](https://github.com/user-attachments/assets/c0b52cc9-48ca-4bdc-99ea-49bee9efbd48)

## Mobile
![image](https://github.com/user-attachments/assets/96f37b32-9951-444b-9179-408422a73d8a)
![image](https://github.com/user-attachments/assets/5141e8d2-0fbb-4c89-bc68-74772d42f86a)

2024-08-26 10:42 UTC, JohnVeness commented
Hi, thanks for working on this.

It's probably not a feature that someone would use if they regularly read articles as they come out, or if they just read articles they are particularly interested in. For me, I find it useful if I want to catch up on a project that is new to me, or which I haven't checked on in some months. In those cases, I click on the oldest new article, read it, click on the next article link at the bottom, and so on. This is more comfortable (and usually quicker, depending on site speed) than navigating back and finding the next article manually.

If there are no overriding negatives about this feature, I would still vote for it being there, even if its use is minimal.

2024-08-26 13:40 UTC, coppolaemilio commented
Chatted a bit with @Calinou and it seems like yes, people do use it, so I guess I'll merge 😅 

Thanks!

2024-08-26 13:40 UTC, merged