Mark GodotCon event as past event on Community page
godotengine/godot-website pull request #759
Opened 2023-11-29 22:18 UTC by Calinou

2023-11-29 22:23 UTC, akien-mga approved these changes

2023-11-29 22:29 UTC, YuriSizov requested changes
This bit should be commented out until the next planned event, instead of the word change. See the edit history for reference.

2023-11-30 08:36 UTC, YuriSizov approved these changes

2023-11-30 08:36 UTC, merged

2023-11-30 08:36 UTC, YuriSizov commented
Looks in order now, thanks!