Add Windows ARM64 download links
godotengine/godot-website pull request #885
Opened 2024-07-28 17:47 UTC by adamscott

This PR:
- adds Windows ARM64 links
  - supports 4.3.rc1 links
- renames Windows links to more standard names for 4.3.rc2 and onwards
  - Standard:
    - windows.64: windows.x86_64.zip _(instead of win64.exe.zip)_
    - windows.32: windows.x86_32.zip _(instead of win32.exe.zip)_
    - windows.arm64: windows.arm64.zip _(instead of windows_arm64.exe.zip)_
  - Mono:
    - windows.64: mono_windows_x86_64.zip _(instead of mono_win64.zip)_
    - windows.32: mono_windows_x86_32.zip _(instead of mono_win32.zip)_
- adds x86 and x86_64 tags
- did some reordering/cleanup in download_configs.yml
  - removed the weird space between extras and mono
  - put extras after mono

2024-07-28 20:25 UTC, Calinou commented
Do we have to display "Standard" and "Universal" next to all download names? I thought "Standard" was the opposite of ".NET" anyway…

2024-08-01 15:52 UTC, akien-mga requested changes
Haven't reviewed yet, but just marking that this shouldn't be merge without my review.

Renaming binaries here means change the way we do our official builds to match that, so I need to work on that in parallel.

2024-08-01 19:47 UTC, adamscott commented
I pushed a change so that RC1 and RC2 will use the same current file names.

2024-08-05 04:01 UTC, mhilbrunner commented
Consistency is great, and this is definitely an improvement I've wished for in that regard.

Still, this has a cost. I had to redo our automations/CI scripts 3 point releases ago for 4.0 at W4, now this will make us touch these again. Its not a huge thing, but is an annoyance, and I'm not 100% sure it is worth it to incur that to everyone for a bit more consistency. The nerd in me likes the improvement, but at some point we should stop breaking people's stuff constantly, because we can *always* improve stuff, and it does get tiresome eventually.

Long text to say *not sure if worth*.

2024-08-07 14:30 UTC, Repiteo commented
@mhilbrunner In a vacuum, I could see this point having more weight. However, given this is accompanied with adding a new link outright, it feels entirely within scope to make adjustments to other links.

2024-08-08 11:16 UTC, akien-mga commented
So thinking some more about it, I'm erring more on the side on not renaming the other binaries for now. I already had the concern that Max expressed, and I also lack time to do a deep review and changes to the naming scheme - and we're also super late in the release cycle, with RC3 in the oven and no time to beta-test those changes.

We could do a review and possibly renames for 4.4, or wait for the future release which will drop support for the legacy "mono" binaries, and rename everything at that point.

For now, I would suggest just adding the arm64 binaries with the current `_windows_arm64.zip` pattern.

This can be done in this PR, or in a new one if we want to keep this one as a draft for reference for potential future renames of all binaries.

2024-08-08 13:16 UTC, akien-mga commented on _data/download_platforms.yml
> +  caption: "Standard (x86-64)"
We consistently use `x86_64` in Godot, AFAIK only macOS uses `x86-64` (which they now deprecated :upside_down_face: ), so I would undo that change and make the tag `x86_64`.

2024-08-08 13:16 UTC, akien-mga commented on _data/download_platforms.yml
> +  caption: "Standard (x86-64)"
Actually I'd suggest harmonizing all arch names and tags to the ones we use in Godot:
- `x86_64`
- `x86_32`
- `arm64`
- `arm32`

2024-08-08 13:57 UTC, akien-mga commented on _data/download_platforms.yml
> +    - ARMv7
```suggestion
    - arm32
```

2024-08-08 13:57 UTC, akien-mga commented on _data/download_platforms.yml
> +    - ARMv7
```suggestion
    - arm32
```

2024-08-08 14:02 UTC, akien-mga approved these changes
Looks good to me!

2024-08-08 14:03 UTC, merged

2024-08-08 14:03 UTC, akien-mga commented
Thanks!

2024-08-08 14:27 UTC, adamscott commented
I'm having some issues with the PR, I'm debugging.

<img width="475" alt="Capture d’écran, le 2024-08-08 à 10 27 26" src="https://github.com/user-attachments/assets/29b57c32-1c72-4131-818a-b23fab6af698">

2024-08-10 04:08 UTC, mhilbrunner commented
Yeah, I don't know how but I misread this as also changing the URLs of existing downloads for other platforms. May have been looking at different PR? Sorry for the confusion :)